### ISSUE TITLE
Make "pulse" front end work w. story engine spreadsheet

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#1]
Make this front end:
http://xmatthewx.github.io/network-pulse/

Pull data / work with this spreadsheet:
https://docs.google.com/spreadsheets/d/1zeh03mqfHpClO1ijySAUvDZvq_fYARqtGwT0MPmp3EU/edit

**Comment by OpenMatt** [comment]
- @xmatthewx as per our conversations the other day -- are you game? 
- @prefontaine I added a column to the sheet w. a simple "publish? yes or no" field

**Comment by prefontaine** [comment]
@OpenMatt @xmatthewx Great! Thank you. I'm going to add dummy content for now to test the "yes" because need to check if survey respondents gave permission to post publicly. 

I've developed several sites with sort/filter features (mostly for resources: http://tascha.uw.edu/publications-resources/, https://syriaaccountability.org/library/, http://beyondaccess.net/resources/). For the initial front end thinking to filter by:
1. **Focus** — connect leaders, shape agenda, rally citizens
2. **Issue** — #hackable, #open, #privacy, #web4all, #weblit
3. **Potential Users** — Communications, Curriculum Design, Grants & Partnerships, Internet of Things, M&E, Mozilla Clubs, Mozilla Science Lab, Network Members, Policy & Advocacy, State of the Web, Women & Web Literacy
4. **Region** — ALL, Africa, East Asia & the Pacific, Europe & Central Asia, Latin America & the Caribbean, Middle East & North Africa, North America, South Asia

Sorting can be alpha and recency. Later we can add a search. Please let me know if you want me to make a mockup. 

@xmatthewx Happy to jump on a call if that is easiest.

**Comment by prefontaine** [comment]
@xmatthewx Actually I do think I'll need to mock up because we won't pull from all spreadsheet columns. I'll base it on http://xmatthewx.github.io/network-pulse/.

**Comment by prefontaine** [comment]
Hmmmm @xmatthewx http://xmatthewx.github.io/network-pulse/ seems to be not working. Hung up on "loading"... (BTW my email is christine@facilitatingchange.org + skype is christine_prefontaine should you need to contact me off of GitHub).

**Comment by OpenMatt** [comment]
@xmatthewx I have the same issue -- any reason why Pulse would be down?

**Comment by OpenMatt** [comment]
Let's close and revisit pending https://github.com/MozillaFoundation/Story-Engine/issues/7
