### ISSUE TITLE
Ensure London All Hands stories are captured

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#4]

**Comment by prefontaine** [comment]
@OpenMatt I can capture these. Who should I reach out to?

**Comment by OpenMatt** [comment]
@amirad remember all those great personas you guys had up on the wall in London? Any chance we can get those entered through the story tip sheet? Christine can help. 
Story tip sheet is here:
https://docs.google.com/a/mozillafoundation.org/forms/d/1JhujT4NpZRVcQQmDhG1Mc9sgzNC83eD4gXr-8ICZYLM/viewform

**Comment by OpenMatt** [comment]
Looks like Amira is away until July 20.

**Comment by prefontaine** [comment]
@OpenMatt Okay I'll make a note to ping her when she gets back.

**Comment by amirad** [comment]
Hey hey! I have the hard copies in the Dumbo office which I won't be heading to until next week. There are a lot of them though and not sure I have capacity in next couple weeks to input them. Also there were a few people who flagged that they didn't want their personas inputted in the storyengine (I asked when in London) but don't know which ones. We will need Meghan to help us figure that part out.

**Comment by amirad** [comment]
Totally open to anyone else in NYC to help input them into the form.

**Comment by prefontaine** [comment]
Thanks, Amira! Even just some stories would be great -- I'd go for some
good examples, especially the ones that really brought issues to life,
versus being super comprehensive.

Matt we should discuss the private/public aspects. It should be okay for
some stories to remain private and only be used for feedback and
theory-building.

**Comment by prefontaine** [comment]
@OpenMatt @amirad — Back from summer vacation and checking in on this. Meghan had also mentioned these stories. She suggested I check in with Sam Burton.

**Comment by OpenMatt** [comment]
@chrislarry33 is there someone in the NY office that we could ask to do some data entry on this? Basically just need someone to do an hour or so's worth of turning physical copies into digital form. 

@prefontaine Sam Burton is not the right person on this one. I think the main blocker is we just need someone to do the data entry.

**Comment by amirad** [comment]
Hey all! Sorry for the delay in coming back to this. Meghan has taken the personas and documented them for use in some community mapping. I've gone over this with the team and since there were many concerns over content that was shared and making it public, it has been suggested that the personas be used for internal/private use only. Some of the information contain sensitive information and some inaccurate (as people were told to guess behaviours of others) and some people don't feel comfortable the names of their network members being inputted without them leading the conversation. 

I hope this makes sense. Meghan has been creating a beautiful one-MLN story using the personas that might be available for future sharing. I would talk to her about particular stories to share or how to share the broader narrative. (I can't find her on github!)

**Comment by OpenMatt** [comment]
got it! thanks for clarifying Amira -- and no problem. makes total sense.
