### ISSUE TITLE
Make tech decision for database front-end

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#7]
Goal is a simple visual interface for:
- seeing stories sorted by tag (e.g., issue tag, impact tag)

Options:
a) Pulse. tweaked version. working w. (@matthew)
b) Stori.es. https://www.stori.es/signin.jsp reuse open source codebase Consumers Union developed
c) WP plug-in Christine has sourced
d) something else. a lightweight way to visualize / tag / sort data in a spreadsheet.

**Comment by OpenMatt** [comment]
@prefontaine where do we stand on (c)? is that blocked on having your developer do some additional work? maybe we should start with that as our best potential option, since it's the shortest potential path to done?

**Comment by mmmavis** [comment]
@OpenMatt did you mean to tag @xmatthewx instead? 😄

**Comment by OpenMatt** [comment]
yes thank you!

**Comment by prefontaine** [comment]
@OpenMatt I had a convo with @xmatthewx on Friday. We are going to see if we can have one form that folks fill out for both Pulse and StoryEngine tips. I'm waiting to hear back from @xmatthewx. So that is option (a) and covers the tips. In addition, I'm going to chunk up the story and put that into a spreadsheet, so it can be displayed using the same tech (although I do have some questions regarding display -- specifically if I can insert HTML in cells). We can work together on UX for filtering and sorting. Item (c) was a different thing... this was about the coding and analysis of the stories. Ned is not available until October. In the meantime, I've done some research and found two good possibilities. I'm researching an R-based option because it is FOSS and will allow us to do deeper analysis later on (RQDA). There was another cool option that is super simple option (http://www.saturateapp.com/) but you don't have control over where your data sits and that makes me super nervous.

**Comment by xmatthewx** [comment]
Following my meeting with @prefontaine, I oriented our designer, developer, and program/community lead to the project. We clarified how these two initiatives overlap and diverge. 

### Notes
- **Input**: Both projects seek to maximize input. They depend on a process with program staff. Intrinsic motivators will also be valuable. Input should make reporting and program review easier. 
- **Categorization**: Both projects should share common categorization. 
- **Privacy**: Story tips will contain private information we should not display publicly. Assets, on the other hand, will benefit from sharing to increase input and impact. Therefore.... these forms should remain separate (we can't hide spreadsheet entries from prying eyes, even if some items aren't displayed). Forms be linked from a single space to build shared momentum. 
- **Interviews/Stories**: The interview/story can be filed alongside assets useful to staff and network peers. Pulse will contain common meta-data and then link out to assets. It could easily do the same for an interview/story that is posted on Wordpress or elsewhere. Staff could utilize interviews, even if they don't land on Medium via Kevin. Interviews _could_ be included on the platform, but at this stage it seems better to optimize like a card catalog or knowledge base.
- **Scope**: This project will enable filing, sorting, browsing, searching, sharing. Tracking interviews, coding and analysis are best handled by other tools made for those tasks. 

Do these notes ring true to you @prefontaine?  

### Next steps
- @prefontaine, are there any changes you would need to our input form to file a link to an interview/story? Want to give it a try? 

Prototype now appears at http://mozilla.github.io/network-pulse/. You can now share a link to an individual item. (It'll look nicer later today or Monday 😄)

Lastly, if this plan doesn't make sense. Our code is now nice and clean. We can easily make a copy to populate with your story tips. We just might need to hide access behind a password.

**Comment by prefontaine** [comment]
Hi @xmatthewx. Thanks for this summary.

The fields I need to have a story filed are marked as mandatory on this
form. As is, the pulse one won't work for StoryEngine.

Thinking more about our discussion the difference between Network Pulse and
StoryEngine is that the latter focuses on humans/organizations as opposed
to makes/artifacts. Of course, the tow are closely connected. People will
discuss hings that they have made (at which point for sure I would use this
form), or when we want to delve deeper into the people/orgs behind an
artifacts.

I'm wondering if we can use a form that has a skip pattern, starting out by
asking if this is about a person/org or an artifact -- and then directing
to Pulse or StoryEngine.

Re displaying tips. @OpenMatt indicated that it would be valuable to have
both the tips and the stories accessible to staff (with filter, sort,
search). But, because StoryEngine will include lots of personal
information, I suggest we focus on displaying those stories that we have
permission to post. Not displaying tips. Part of the rationale for
displaying tips was so that people could see something tangible quickly
— I’m wondering if that need can be met with timely follow up — and
specifically getting the interview done.

I'll be on vacation for the next three weeks, with limited Internet access.
But when I get back I'd love to discuss this further. With a focus on
building up the pipeline of tips/interviews, and looking at out we can
align categorization. I'll add a screenshot of what I have now in RQDA,
however this is still under development.

**Comment by prefontaine** [comment]
Here is setup for the qualitative data analysis file attributes, file categories, code categories, and codes (this will especially change as we are using grounded theory approach). 
![attributes](https://cloud.githubusercontent.com/assets/892229/17265561/06766ad6-55be-11e6-9531-47c63f557bf5.png)
![file-categories](https://cloud.githubusercontent.com/assets/892229/17265565/08f75ffe-55be-11e6-8742-5a438e76a6b8.png)
![code-categories](https://cloud.githubusercontent.com/assets/892229/17265566/0ae858e0-55be-11e6-93b1-40dc06953af8.png)
![codes_will_change](https://cloud.githubusercontent.com/assets/892229/17265568/0cb29f28-55be-11e6-8436-cd02b40080af.png)

**Comment by OpenMatt** [comment]
Hi, guys! I'm fresh back from vacation myself and just getting caught up. 

@xmatthewx re: "We can easily make a copy to populate with your story tips. We just might need to hide access behind a password."

could you go ahead and do that? that way @prefontaine and I can play around with the prototype as it already exists. and maybe I can come up with some ways to work around / social hack the issues christine mentioned. or at the very least, come away with a better understanding of how it works already so we can file smarter tickets for tweaks or feature requests we might want to make. 

possible?

**Comment by xmatthewx** [comment]
I just posted a link to your Robby Kraft Tumbleweed interview to Pulse (https://mzl.la/pulse). @KevZawacki has entered links to several news articles into Pulse as well. Pulse serves as a knowledge base or card catalog, linking out to assets that take many forms. 

> I'm wondering if we can use a form that has a skip pattern, starting out by asking if this is about a person/org or an artifact

Definitely. I think it's useful to make this a one-stop experience for input, even if we split traffic after the initial step.

**Comment by xmatthewx** [comment]
@OpenMatt – want to schedule a time to spin up an instance for you to hack on? We can get it on your github account. I have a couple of questions, but it shouldn't take us more than 15 or 20 minutes together.

**Comment by OpenMatt** [comment]
sounds good! let’s do it Thurs?

**Comment by prefontaine** [comment]
@xmatthewx Thanks for posting that story example. Not sure what Tumbleweed is though — this story links to the raw interview on StoryEngine. Is that link wrong? Also... note that @OpenMatt this is a story for which we have permission. When I get back from vacation maybe we can brainstorm those for which we don't. For example Shauna was not comfortable providing permission for the interview that I did with her. I have to get back to her if it is possible if we change some of the language on the release.

**Comment by xmatthewx** [comment]
Tumbleweed is the name Robby gave to the hack day project. It appears in both of your links under Evidence. We can experiment with how we title and frame these. In fact...

I posted a duplicate link to the interview, this time with the title "[Interview: Robby Kraft on NASA Challenge](https://mzl.la/pulse?id=p1470866187000)". You can see both version if you tap "Latest" in the menu. 

Glad to make any edits you want.

**Comment by prefontaine** [comment]
@OpenMatt just checking in on this. We're putting on back burner while we move ahead with interviews, posting our stories on StoryEngine.io, and coding?

**Comment by OpenMatt** [comment]
yup. let's back-burner now that we a) have Pulse working in a prototype-y way, and b) have agreed to prioritize story production. 

I'm going to close. We can always re-open later.
