### ISSUE TITLE
Tighten synch w. Comms + Marketing

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/Story-Engine#89]
Schedule a recurring editorial calendar call w. comms and marketing. Ideally: in the first week of each heartbeat.

Topics:

* editorial calendar (understanding key themes upcoming, making suggestions based on content, etc.) 
* being clear about the delivery process around new stories for Marketing + Comms (e.g., cc Kevin + Paul on story notification emails to the interviewee?) 
* best ways to occasionally loop in MoCo Marketing on this content. They've already said they like it.

**Comment by prefontaine** [comment]
@KevZawacki @hpauljohnson Can we schedule a time to check in the week after next? I'm starting to get more intentional about promoting stories after I post them. Some are getting good traction on social media (example: https://storyengine.io/stories/open-innovation/christie-bahlai/). Would like to improve process of letting you know when we publish / when we see patterns. You can use these links to pick best time/day:

https://calendly.com/christine-prefontaine/60-minute-call/
https://calendly.com/christine-prefontaine/45-minute-call/
https://calendly.com/christine-prefontaine/30-minute-call/

**Comment by OpenMatt** [comment]
plus @Lottarao as well, as the new head of MoFo communications :)

**Comment by prefontaine** [comment]
@KevZawacki @hpauljohnson — Can we reschedule this week or next? Would very much like to synch up StoryEngine with your work.

**Comment by KevZawacki** [comment]
@prefontaine Let's do next week -- Lotta will join us. Tuesday at 1pm ET? Just sent a calendar invite.

**Comment by prefontaine** [comment]
Awesome! It's on my calendar. Just need link to your Vidyo room since I'm
not in the internal system. Looking forward.

**Comment by KevZawacki** [comment]
@prefontaine My room link: https://v.mozilla.com/flex.html?roomdirect.html&key=zFGjeCShpKN0s0smfq1fyCAD8o

**Comment by prefontaine** [comment]
Excellent. Thank you.

**Comment by OpenMatt** [comment]
Marking this done. We will schedule a new monthly recurring meeting to synch w. Comms + Marketing on editorial calendar, etc.
